import Foundation
import FaceTecSDK

@objc(Facetec)
class Facetec: NSObject, RCTBridgeModule {
  static func moduleName() -> String {
    return "Facetec";
  }

  static func requiresMainQueueSetup() -> Bool {
    return true;
  }

  @objc
  func setup(_ appTheme: String, resolver: @escaping RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) -> Void {
    Config.initializeFaceTecSDKFromAutogeneratedConfig(completion: { initializationSuccessful in
      resolver(nil);
    });
    ThemeHelpers.setAppTheme(theme: appTheme);
  }

  @objc
  func initialization(_ resolver: @escaping RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) -> Void {
    print("initialization")
    _ = BaseProcessor(requestPath: "/initialization", resolver: resolver);
  }

  @objc
  func authorization(_ resolver: @escaping RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) -> Void {
    _ = BaseProcessor(requestPath: "/authorization", resolver: resolver);
  }
}
